### ISSUE TITLE
.Net program not working properly

### ISSUE THREAD

**Issue by DistantWolf** [Offensive-Panda/.NET_PROFILER_DLL_LOADING#1]
Brother, when I used this project to perform UAC Bypass testing, I found that when I executed the .Net program through the execute-assemble instruction of CobaltStrike, it did not work properly. Could you please provide some suggestions?

**Comment by Offensive-Panda** [comment]
> Brother, when I used this project to perform UAC Bypass testing, I found that when I executed the .Net program through the execute-assemble instruction of CobaltStrike, it did not work properly. Could you please provide some suggestions?

Make sure the path of DLL is changed as per your directory, I am loading it from public folder. More I can tell you after seeing the error.

**Comment by DistantWolf** [comment]
OK, thank you brother. After I renamed the dll file, the .Net program resumed normal operation. Since I am a new red team member, I still don't understand why other .Net programs can still load the DLL in the public directory after deleting the registry related information. If you find the cause of the problem and reply to me, I will be grateful.😄

**Comment by Offensive-Panda** [comment]
COM registration using CLSIDs heavily relies on registery, but sometimes .NET programs used explicit methods. (ENVIRONMENT PATH). In this case, if environment variables and registery paths are deleted, it shouldn't.

**Comment by DistantWolf** [comment]
buddy, thanks for helping me solve my doubts. I often learn from your articles and GitHub projects, which provide me with great help. Thank you for sharing, have a nice day!
